### ISSUE TITLE
demo无法正确运行测试用例

### ISSUE THREAD

**Issue by myDonghao** [zhenghongyi/YIHtmlParser#1]
测试用例报错！希望大大看一下！

**Comment by myDonghao** [comment]
![image](https://user-images.githubusercontent.com/20014338/84144343-b0677380-aa8a-11ea-9ac0-70b54c8b0d35.png)

**Comment by zhenghongyi** [comment]
在handleWithXPathQuery方法里的判断应该是
`if (nodes != nil && nodes != NULL)`
抱歉了，晚上回去再更新代码

**Comment by zhenghongyi** [comment]
你好，已经更新

**Comment by myDonghao** [comment]
感谢大大，我之前搞了一个是利用正则匹配加字符串替换来搞的，灵活度很弱，然后现在可以找到的解析并编辑HTML的，好像就你这一个库了！嘿嘿。

**Comment by zhenghongyi** [comment]
已支持pod安装，欢迎使用，希望能帮到你！
